spring:
  profiles:
    active: prod
  liquibase:
    changelog: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8080

logging:
  level:
    root: info
    com.example: debug









