spring:
  datasource:
    username: sa
    password: null
    url: jdbc:h2:mem:jobsearchdb
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

    show-sql: true